console.log(2-1);
console.log(2+2);
var x=3*3;
console.log(x);
var y=7/2;
console.log(y);
console.log(7%2);
console.log('____________');
console.log(x++);
console.log(++x);
console.log(x--);
console.log(10**2);
console.log(10+true);
console.log(10+Infinity);
console.log(10+NaN);
console.log(10+false);
console.log(10+'a');
console.log(10*'a');
console.log(10*'10');
console.log(10+'10');
console.log(10-'10');